
[general]

	[general.eeeeee]
		selector = 0
		percent_slider = 0.0

	[general.category]
		password = ""
		color_picker = "255,0,0,255"
		"do_action!!!" = false
		text = ""

["not_general!"]
	checkbox = false

